# Generated by Django 5.0.3 on 2024-03-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=666)),
                ('password', models.CharField(max_length=666)),
                ('mobile', models.CharField(max_length=666)),
                ('gender', models.CharField(max_length=8)),
                ('registerTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
